spring:
  application:
    name: jarFactory

  datasource:
    url: jdbc:postgresql://postgres:5432/jar_factory
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
max-factory-capacity:
  L_jar: 35 000
  M_jar: 35 000
  S_jar: 35 000
