server:
  port: 8100
spring:
  application:
    name: jarFactory

  datasource:
    url: jdbc:postgresql://localhost:5432/jar_factory
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
max-factory-capacity:
  L_jar: 35 000
  M_jar: 35 000
  S_jar: 35 000
