openapi: 3.0.3
info:
  title: JarFactory API
  version: 1.0.0
  description: API for ordering jars from the JarFactory

servers:
  - url: http://localhost:8080

tags:
  - name: Orders
    description: Endpoints related to ordering jars.

paths:
  /jars/order:
    post:
      tags:
        - Orders
      summary: Create a new jar order
      operationId: createJarOrder
      requestBody:
        description: Order details for jars
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deliveryDate:
                  type: string
                  format: date
                  example: "2024-08-01"
                smallJars:
                  type: integer
                  example: 10
                mediumJars:
                  type: integer
                  example: 5
                largeJars:
                  type: integer
                  example: 2
              required:
                - deliveryDate
                - smallJars
                - mediumJars
                - largeJars
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    example: "123e4567-e89b-12d3-a456-426614174000"
        '422':
          description: Business logic error
          content:
            application/json:
              schema:
                type: object
                properties:
                  rejectReason:
                    type: string
                    example: "zamówienie przekraczajace zdolności produkcyjne"
        '501':
          description: Not Implemented
